### PR TITLE
Changes in Member section

### PR DESCRIPTION
**Pull request by singhvaibhav715**
Added more members in member section

### CODE REVIEW

**Comment by akshat0047** [comment]
Please show a preview for the same using github pages

**Comment by singhvaibhav715** [comment]
https://singhvaibhav715.github.io/asetaliaslucknow.github.io/

**Comment by vips28** [comment]
@singhvaibhav715  Kindly add all the members mentioned in the issue i.e.  Umang Jain is left to be added. Squash all the commits above because you cannot make so many commits in any pull request. Also if you have their photographs, add them.

**Comment by akshat0047** [comment]
@singhvaibhav715  Please squash your commits, there are 8 commits, we need one.
Try this:
[Squashing last x commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

**Comment by singhvaibhav715** [comment]
Pulled latest commits and squash done, looks good to merge! @akshat0047

**Pull request merged**
